on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choice Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the application
        run: echo "The Application is Deployed, wink wink!"
