on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
      - "package.json"
      - "!README.md"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run tests
        run: npm test
